#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 12, 2020 05:19:48 PM IST  platform: Windows NT

import sys
import psycopg2
from psycopg2 import sql
from tkinter import messagebox

con = psycopg2.connect(database ="payment", user = "postgres", password = "root", host = "127.0.0.1", port = "5432" )
cur = con.cursor()

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def delete1(p1):
    Name = w.name_1.get()
    Name = Name.lower()
    cur.execute("DELETE FROM biodata WHERE name =%s", [Name])
    messagebox.showinfo("vsa",Name.title()+"'s biodata deleted")
    w.name_1.delete(0,100)
    con.commit()
    
def delete2(p1):
    Name = w.name_2.get()
    Name = Name.lower()
    cur.execute(sql.SQL("DROP TABLE advance.{}").format(sql.Identifier(Name)))
    messagebox.showinfo("vsa","Whole Advance Datas of "+ Name.title()+" is Completely Deleted")
    w.name_2.delete(0,100)
    con.commit()
    
def delete3(p1):
    Name = w.name_3.get()
    Name = Name.lower()
    Date = date
    cur.execute(sql.SQL("DELETE FROM advance.{} where date = %s").format(sql.Identifier(Name)),[Date])
    messagebox.showinfo("vsa",Name.title() +"'s Advance Data Dleted")
    w.name_3.delete(0,100)
    w.date.config(text='')
    con.commit()

def menu(p1):
    top_level.destroy()
    import menu
    menu.vp_start_gui()

def select(p1):
    global date
    date = w.Cal.get_date()
    w.date.config(text=date)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    con.close()
    top_level = None

if __name__ == '__main__':
    import delete
    delete.vp_start_gui()




