#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 07, 2020 01:36:37 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def advance(p):
    top_level.destroy()
    import advance
    advance.vp_start_gui()

def bio(p):
    top_level.destroy()
    import bio
    bio.vp_start_gui()

def delete(p):
    top_level.destroy()
    import delete
    delete.vp_start_gui()
    
def details(p):
    top_level.destroy()
    import details
    details.vp_start_gui()
    
def print(p):
    top_level.destroy()
    import print
    print.vp_start_gui()

def report(p):
    top_level.destroy()
    import report
    report.vp_start_gui()
    
def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import menu
    menu.vp_start_gui()




