#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 11, 2020 03:33:40 PM IST  platform: Windows NT

import sys
from tkcalendar import *

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import print_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Bio (root)
    print_support.init(root, top)
    root.mainloop()

w = None
def create_Bio(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Bio(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Bio (w)
    print_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Bio():
    global w
    w.destroy()
    w = None

class Bio:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Segoe UI} -size 15"
        font11 = "-family {Arial} -size 14"
        font12 = "-family {Segoe UI} -size 15 -weight bold"
        font9 = "-family {Rockwell} -size 20 -weight bold"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1142x800")
        top.minsize(120, 2)
        top.maxsize(1924, 1065)
        top.resizable(1, 1)
        top.title("VSA")
        top.configure(relief="raised")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.l1 = tk.Label(top)
        self.l1.place(relx=0.263, rely=0.025, height=72, width=551)
        self.l1.configure(activebackground="#f9f9f9")
        self.l1.configure(activeforeground="black")
        self.l1.configure(background="#d9d9d9")
        self.l1.configure(disabledforeground="#a3a3a3")
        self.l1.configure(font="-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0")
        self.l1.configure(foreground="#000000")
        self.l1.configure(highlightbackground="#d9d9d9")
        self.l1.configure(highlightcolor="black")
        self.l1.configure(text='''Print''')

        self.Canvas1 = tk.Canvas(top)
        self.Canvas1.place(relx=0.009, rely=0.125, relheight=0.855
                , relwidth=0.984)
        self.Canvas1.configure(background="#ffffff")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="blue")
        self.Canvas1.configure(selectforeground="white")

        self.TSeparator1 = ttk.Separator(self.Canvas1)
        self.TSeparator1.place(relx=0.525, rely=0.044, relheight=0.923)
        self.TSeparator1.configure(orient="vertical")

        self.Label1 = tk.Label(self.Canvas1)
        self.Label1.place(relx=0.16, rely=0.073, height=61, width=312)
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Print By Name''')

        self.Label1_1 = tk.Label(self.Canvas1)
        self.Label1_1.place(relx=0.667, rely=0.058, height=61, width=312)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#ffffff")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font="-family Rockwell -size 20 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''Print By Date''')

        self.Cal1 = Calendar(self.Canvas1, selectmode = "day",date_pattern ="y-mm-dd")
        self.Cal1.place(relx=0.062, rely=0.365, relheight=0.373, relwidth=0.227)

        self.Cal2 = Calendar(self.Canvas1, selectmode = "day",date_pattern ="y-mm-dd")
        self.Cal2.place(relx=0.552, rely=0.234, relheight=0.404, relwidth=0.262)

        self.select1 = tk.Button(self.Canvas1)
        self.select1.place(relx=0.300, rely=0.620, height=44, width=77)
        self.select1.configure(activebackground="#ececec")
        self.select1.configure(activeforeground="#000000")
        self.select1.configure(background="#d9d9d9")
        self.select1.configure(disabledforeground="#a3a3a3")
        self.select1.configure(foreground="#000000")
        self.select1.configure(highlightbackground="#d9d9d9")
        self.select1.configure(highlightcolor="black")
        self.select1.configure(pady="0")
        self.select1.configure(text='''Starting''')
        self.select1.bind('<Button-1>',lambda e:print_support.select1(e))

        self.select2 = tk.Button(self.Canvas1)
        self.select2.place(relx=0.400, rely=0.620, height=44, width=77)
        self.select2.configure(activebackground="#ececec")
        self.select2.configure(activeforeground="#000000")
        self.select2.configure(background="#d9d9d9")
        self.select2.configure(disabledforeground="#a3a3a3")
        self.select2.configure(foreground="#000000")
        self.select2.configure(highlightbackground="#d9d9d9")
        self.select2.configure(highlightcolor="black")
        self.select2.configure(pady="0")
        self.select2.configure(text='''Ending''')
        self.select2.bind('<Button-1>',lambda e:print_support.select2(e))


        self.select3 = tk.Button(self.Canvas1)
        self.select3.place(relx=0.827, rely=0.439, height=44, width=77)
        self.select3.configure(activebackground="#ececec")
        self.select3.configure(activeforeground="#000000")
        self.select3.configure(background="#d9d9d9")
        self.select3.configure(disabledforeground="#a3a3a3")
        self.select3.configure(foreground="#000000")
        self.select3.configure(highlightbackground="#d9d9d9")
        self.select3.configure(highlightcolor="black")
        self.select3.configure(pady="0")
        self.select3.configure(text='''Select''')
        self.select3.bind('<Button-1>',lambda e:print_support.select3(e))

        self.date1 = tk.Label(self.Canvas1)
        self.date1.place(relx=0.338, rely=0.424, height=41, width=113)
        self.date1.configure(background="#ffffff")
        self.date1.configure(font="TkFixedFont20")
        self.date1.configure(disabledforeground="#a3a3a3")
        self.date1.configure(foreground="#000000")
        self.date1.configure(relief="raised")

        self.date2 = tk.Label(self.Canvas1)
        self.date2.place(relx=0.338, rely=0.500, height=41, width=113)
        self.date2.configure(background="#ffffff")
        self.date2.configure(font="TkFixedFont20")
        self.date2.configure(disabledforeground="#a3a3a3")
        self.date2.configure(foreground="#000000")
        self.date2.configure(relief="raised")


        self.date3 = tk.Label(self.Canvas1)
        self.date3.place(relx=0.836, rely=0.278, height=41, width=113)
        self.date3.configure(activebackground="#f9f9f9")
        self.date3.configure(activeforeground="black")
        self.date3.configure(background="#ffffff")
        self.date3.configure(font="TkFixedFont20")
        self.date3.configure(disabledforeground="#a3a3a3")
        self.date3.configure(foreground="#000000")
        self.date3.configure(highlightbackground="#d9d9d9")
        self.date3.configure(highlightcolor="black")
        self.date3.configure(relief="raised")

        self.Label2 = tk.Label(self.Canvas1)
        self.Label2.place(relx=0.053, rely=0.249, height=41, width=203)
        self.Label2.configure(background="#ffffff")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font10)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Enter the Name''')

        self.name = tk.Entry(self.Canvas1)
        self.name.place(relx=0.24, rely=0.249,height=40, relwidth=0.235)
        self.name.configure(background="white")
        self.name.configure(disabledforeground="#a3a3a3")
        self.name.configure(font=font11)
        self.name.configure(foreground="#000000")
        self.name.configure(insertbackground="black")

        self.prints1 = tk.Button(self.Canvas1)
        self.prints1.place(relx=0.311, rely=0.775, height=54, width=137)
        self.prints1.configure(activebackground="#ececec")
        self.prints1.configure(activeforeground="#000000")
        self.prints1.configure(background="#454545")
        self.prints1.configure(disabledforeground="#a3a3a3")
        self.prints1.configure(font=font12)
        self.prints1.configure(foreground="#ffffff")
        self.prints1.configure(highlightbackground="#d9d9d9")
        self.prints1.configure(highlightcolor="black")
        self.prints1.configure(pady="0")
        self.prints1.configure(text='''Print''')
        self.prints1.bind('<Button-1>',lambda e:print_support.prints1(e))

        self.prints2 = tk.Button(self.Canvas1)
        self.prints2.place(relx=0.783, rely=0.702, height=54, width=137)
        self.prints2.configure(activebackground="#ececec")
        self.prints2.configure(activeforeground="#000000")
        self.prints2.configure(background="#454545")
        self.prints2.configure(disabledforeground="#a3a3a3")
        self.prints2.configure(font="-family {Segoe UI} -size 15 -weight bold -slant roman -underline 0 -overstrike 0")
        self.prints2.configure(foreground="#ffffff")
        self.prints2.configure(highlightbackground="#d9d9d9")
        self.prints2.configure(highlightcolor="black")
        self.prints2.configure(pady="0")
        self.prints2.configure(text='''Print''')
        self.prints2.bind('<Button-1>',lambda e:print_support.prints2(e))
        

        self.menu = tk.Button(self.Canvas1)
        self.menu.place(relx=0.872, rely=0.892, height=54, width=117)
        self.menu.configure(activebackground="#ececec")
        self.menu.configure(activeforeground="#000000")
        self.menu.configure(background="#d9d9d9")
        self.menu.configure(disabledforeground="#a3a3a3")
        self.menu.configure(foreground="#000000")
        self.menu.configure(highlightbackground="#d9d9d9")
        self.menu.configure(highlightcolor="black")
        self.menu.configure(pady="0")
        self.menu.configure(text='''Back''')
        self.menu.bind('<Button-1>',lambda e:print_support.menu(e))

if __name__ == '__main__':
    vp_start_gui()





