#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 11, 2020 03:33:46 PM IST  platform: Windows NT

import sys
import psycopg2
from psycopg2 import sql
from tkinter import messagebox
from columnar import *
import os

con = psycopg2.connect(database ="payment", user = "postgres", password = "root", host = "127.0.0.1", port = "5432" )
cur = con.cursor()

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def menu(p1):
    top_level.destroy()
    import menu
    menu.vp_start_gui()

def select1(p1):
    global Date1
    Date1 = w.Cal1.get_date()
    w.date1.config(text=Date1)

def select2(p1):
    global Date2
    Date2 = w.Cal1.get_date()
    w.date2.config(text=Date2)

def select3(p1):
    global Date3
    Date3 = w.Cal2.get_date()
    w.date3.config(text=Date3)

def prints1(p1):
    
    Name = w.name.get()
    Name = Name.lower()
    date1 = Date1
    date2 = Date2
    fi=open(r"out.txt","w+")  
    headers = ['Si.No', 'Account Name', 'Account Number', 'Bank Name', 'Branch Name', 'IFSC', 'Amount', 'Reason']      
    s=1
    cur.execute(sql.SQL("SELECT amt, reason FROM advance.{} WHERE date BETWEEN %s AND %s").format(sql.Identifier(Name)),[date1, date2])
    rows = cur.fetchall()
    for row in rows:
        Amount = row[0]
        Reason = row[1]
        cur.execute("SELECT * FROM biodata WHERE name = %s",[Name])
        rows = cur.fetchall()
        for row in rows:
            fi.write("{0}".format(s))
            fi.write(",")
            fi.write("{0}".format(row[3].capitalize()))
            fi.write(",")
            fi.write("{0}".format(row[2]))
            fi.write(",")
            fi.write("{0}".format(row[4].upper()))
            fi.write(",")
            fi.write("{0}".format(row[5].capitalize()))
            fi.write(",")
            fi.write("{0}".format(row[6].upper()))
            fi.write(",")
            fi.write("Rs.")
            fi.write("{0}".format(Amount))
            fi.write(",")
            fi.write("{0}".format(Reason.upper()))
            fi.write("\n")

    fi.close()
    a_file = open(r"out.txt", "r")
    list_of_lists = []
    for line in a_file:
        stripped_line = line.strip()
        line_list = stripped_line.split(',')
        list_of_lists.append(line_list)
    a_file.close()
    table = columnar(list_of_lists, headers, no_borders=False, column_sep=' ', max_column_width=200, terminal_width= 10*10)
    fin=open(r"print.txt","w+")
    fin.write(table)
    fin.close()
    file = "notepad.exe print.txt"
    os.system(file)


def prints2(p1):
    try:

        Date = Date3
        fi=open("out.txt","w+")  
        headers = ['Si.No', 'Account Name', 'Account Number', 'Bank Name', 'Branch Name', 'IFSC', 'Amount', 'Reason']      
        s=1
        cur.execute("SELECT table_name FROM information_schema.tables WHERE table_schema='advance' ")
        rows = cur.fetchall()
        for row in rows:
            Name = row[0]
            cur.execute(sql.SQL("SELECT amt, reason FROM advance.{} WHERE date = %s").format(sql.Identifier(Name)),[Date])
            rows = cur.fetchall()
            for row in rows:
                Amount = row[0]
                Reason = row[1]
                cur.execute("SELECT * FROM biodata WHERE name = %s",[Name])
                rows = cur.fetchall()     
                for row in rows:
                    fi.write("{0}".format(s))
                    fi.write(",")
                    fi.write("{0}".format(row[3].title()))
                    fi.write(",")
                    fi.write("{0}".format(row[2]))
                    fi.write(",")
                    fi.write("{0}".format(row[4].upper()))
                    fi.write(",")
                    fi.write("{0}".format(row[5].capitalize()))
                    fi.write(",")
                    fi.write("{0}".format(row[6].upper()))
                    fi.write(",")
                    fi.write("Rs.")
                    fi.write("{0}".format(Amount))
                    fi.write(",")
                    fi.write("{0}".format(Reason.upper()))
                    fi.write("\n")
                    s+=1

        fi.close()
        a_file = open("out.txt", "r")
        list_of_lists = []
        for line in a_file:
            stripped_line = line.strip()
            line_list = stripped_line.split(',')
            list_of_lists.append(line_list)
        a_file.close()
        table = columnar(list_of_lists, headers, no_borders=False, column_sep=' ', max_column_width=200, terminal_width= 10*10)
        fin=open("print.txt","w+")
        fin.write(table)
        fin.close()
        file = "notepad.exe print.txt"
        os.system(file)

    except:
        messagebox.showerror("vsa","Select the correct date")
        top_level.destroy()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None
    con.close()

if __name__ == '__main__':
    import print
    print.vp_start_gui()




