#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 13, 2020 10:57:04 AM IST  platform: Windows NT

import sys
import psycopg2
from psycopg2 import sql
from tkinter import messagebox
from columnar import *
import os

con = psycopg2.connect(database ="payment", user = "postgres", password = "root", host = "127.0.0.1", port = "5432" )
cur = con.cursor()

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def menu(p1):
    top_level.destroy()
    import menu
    menu.vp_start_gui()

def prints(p1):

    cur.execute("CREATE TEMP TABLE report(name VARCHAR(80), site VARCHAR(30), date DATE, amt INTEGER, reason VARCHAR(100))")
    fi=open(r"out.txt","w+")  
    headers = ['Si.No', 'Name', 'Site', 'Date', 'Amount', 'Reason']      
    s=1
    cur.execute("SELECT table_name FROM information_schema.tables WHERE table_schema='advance' ")
    rows = cur.fetchall()
    for row in rows:
        Name = row[0]
        cur.execute(sql.SQL("INSERT INTO report(SELECT * FROM advance.{} where date between %s and %s)").format(sql.Identifier(Name)),[Date1, Date2])
    cur.execute("SELECT * FROM report ORDER BY date ASC")
    rows = cur.fetchall()
    for row in rows:
        fi.write("{0}".format(s))
        fi.write(",")
        fi.write("{0}".format(row[0].title()))
        fi.write(",")
        fi.write("{0}".format(row[1].capitalize()))
        fi.write(",")
        fi.write("{0}".format(row[2]))
        fi.write(",")
        fi.write("Rs.")
        fi.write("{0}".format(row[3]))
        fi.write(",")
        fi.write("{0}".format(row[4].upper()))
        fi.write("\n")
        s+=1

    fi.close()
    a_file = open(r"out.txt", "r")
    list_of_lists = []
    for line in a_file:
        stripped_line = line.strip()
        line_list = stripped_line.split(',')
        list_of_lists.append(line_list)
    a_file.close()
    table = columnar(list_of_lists, headers, no_borders=False, column_sep=' ', max_column_width=200)
    fin=open(r"print.txt","w+")
    fin.write(table)
    fin.close()
    file = "notepad.exe print.txt"
    os.system(file)
    w.date_1.config(text='')
    w.date_2.config(text='')
    cur.execute("DROP TABLE report")
    
    
def select_1(p1):
    global Date1
    Date1 = w.Cal_1.get_date()
    w.date_1.config(text=Date1)

def select_2(p1):
    global Date2
    Date2 = w.Cal_2.get_date()
    w.date_2.config(text=Date2)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    con.close()
    top_level = None

if __name__ == '__main__':
    import report
    report.vp_start_gui()




