#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 13, 2020 10:56:55 AM IST  platform: Windows NT

import sys
from tkcalendar import *

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import report_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    report_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    report_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1008x789")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1, 1)
        top.title("VSA")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.169, rely=0.037, height=89, width=663)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI Black} -size 20 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Prints Weekly Report''')

        self.Cal_1 = Calendar(top, selectmode = "day",date_pattern ="y-mm-dd")
        self.Cal_1.place(relx=0.099, rely=0.319, relheight=0.364, relwidth=0.303)

        self.Cal_2 = Calendar(top, selectmode = "day",date_pattern ="y-mm-dd")
        self.Cal_2.place(relx=0.556, rely=0.319, relheight=0.364, relwidth=0.309)

        self.select_1 = tk.Button(top)
        self.select_1.place(relx=0.169, rely=0.71, height=44, width=117)
        self.select_1.configure(activebackground="#ececec")
        self.select_1.configure(activeforeground="#000000")
        self.select_1.configure(background="#d9d9d9")
        self.select_1.configure(disabledforeground="#a3a3a3")
        self.select_1.configure(foreground="#000000")
        self.select_1.configure(highlightbackground="#d9d9d9")
        self.select_1.configure(highlightcolor="black")
        self.select_1.configure(pady="0")
        self.select_1.configure(text='''Select''')
        self.select_1.bind('<Button-1>',lambda e:report_support.select_1(e))

        self.select_2 = tk.Button(top)
        self.select_2.place(relx=0.655, rely=0.71, height=44, width=117)
        self.select_2.configure(activebackground="#ececec")
        self.select_2.configure(activeforeground="#000000")
        self.select_2.configure(background="#d9d9d9")
        self.select_2.configure(disabledforeground="#a3a3a3")
        self.select_2.configure(foreground="#000000")
        self.select_2.configure(highlightbackground="#d9d9d9")
        self.select_2.configure(highlightcolor="black")
        self.select_2.configure(pady="0")
        self.select_2.configure(text='''Select''')
        self.select_2.bind('<Button-1>',lambda e:report_support.select_2(e))
        

        self.date_1 = tk.Label(top)
        self.date_1.place(relx=0.139, rely=0.228, height=60, width=187)
        self.date_1.configure(activebackground="#f9f9f9")
        self.date_1.configure(activeforeground="black")
        self.date_1.configure(font="-family {Segoe UI Black} -size 20 -weight bold -slant roman -underline 0 -overstrike 0")
        self.date_1.configure(background="#ffffff")
        self.date_1.configure(disabledforeground="#a3a3a3")
        self.date_1.configure(foreground="#000000")
        self.date_1.configure(highlightbackground="#d9d9d9")
        self.date_1.configure(highlightcolor="black")
        self.date_1.configure(relief="raised")

        self.date_2 = tk.Label(top)
        self.date_2.place(relx=0.625, rely=0.228, height=60, width=190)
        self.date_2.configure(activebackground="#f9f9f9")
        self.date_2.configure(activeforeground="black")
        self.date_2.configure(font="-family {Segoe UI Black} -size 20 -weight bold -slant roman -underline 0 -overstrike 0")
        self.date_2.configure(background="#ffffff")
        self.date_2.configure(disabledforeground="#a3a3a3")
        self.date_2.configure(foreground="#000000")
        self.date_2.configure(highlightbackground="#d9d9d9")
        self.date_2.configure(highlightcolor="black")
        self.date_2.configure(relief="raised")

        self.prints = tk.Button(top)
        self.prints.place(relx=0.387, rely=0.824, height=64, width=197)
        self.prints.configure(activebackground="#ececec")
        self.prints.configure(activeforeground="#000000")
        self.prints.configure(background="#4d4d4d")
        self.prints.configure(disabledforeground="#a3a3a3")
        self.prints.configure(font="-family {Segoe UI Black} -size 18 -weight bold -slant roman -underline 0 -overstrike 0")
        self.prints.configure(foreground="#ffffff")
        self.prints.configure(highlightbackground="#d9d9d9")
        self.prints.configure(highlightcolor="black")
        self.prints.configure(pady="0")
        self.prints.configure(text='''prints''')
        self.prints.bind('<Button-1>',lambda e:report_support.prints(e))

        self.menu = tk.Button(top)
        self.menu.place(relx=0.843, rely=0.875, height=34, width=67)
        self.menu.configure(activebackground="#ececec")
        self.menu.configure(activeforeground="#000000")
        self.menu.configure(background="#d9d9d9")
        self.menu.configure(disabledforeground="#a3a3a3")
        self.menu.configure(foreground="#000000")
        self.menu.configure(highlightbackground="#d9d9d9")
        self.menu.configure(highlightcolor="black")
        self.menu.configure(pady="0")
        self.menu.configure(text='''Back''')
        self.menu.bind('<Button-1>',lambda e:report_support.menu(e))

if __name__ == '__main__':
    vp_start_gui()





